
name: update readme tables

on:
  push:
    branches: [ master ]

jobs:
  update-readme:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: update tables
      run: |
        make table
    - name: Commit files
      run: |
        git config --local user.email "eirture@gmail.com"
        git config --local user.name "Jie Liu"
        git commit -m "docs(readme): update readme tables" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
